# Generated by Django 4.2.13 on 2024-05-21 06:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number', models.CharField(verbose_name='Номер телефона', max_length=20)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.person')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chiefs/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Chief',
                'verbose_name_plural': 'Chiefs',
            },
            bases=('main.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('filling', models.CharField(max_length=100, verbose_name='Начинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cakes/', verbose_name='Изображение')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('tags', models.ManyToManyField(related_name='cakes', to='main.tag', verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('design', models.CharField(max_length=100, verbose_name='Дизайн')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('due_date', models.DateField(verbose_name='Срок заказа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Фото дизайна')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='main.person', verbose_name='Клиент')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cake', verbose_name='Торт')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_orders', to='main.chief', verbose_name='Кондитер')),
            ],
        ),
    ]
