# Generated by Django 4.2.13 on 2024-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/media/cakes/', verbose_name='Изображение'),
        ),
    ]
