# Generated by Django 4.2.13 on 2024-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chief_information_alter_cake_weight_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/media/reviews/', verbose_name='Фото'),
        ),
    ]
