# Generated by Django 4.2.13 on 2024-05-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cake_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chief',
            options={'permissions': [('can_add_cake', 'Can add cake')], 'verbose_name': 'Chief', 'verbose_name_plural': 'Chiefs'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Сlient', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='cake',
            name='chief',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='main.chief', verbose_name='Кондитер'),
        ),
    ]
