# Generated by Django 4.2.13 on 2024-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/chiefs/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/reviews/', verbose_name='Фото'),
        ),
    ]
