# Generated by Django 4.2.13 on 2024-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_chief_logo_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_process', 'В процессе'), ('completed', 'Завершен')], default='pending', max_length=20),
        ),
    ]
