# Generated by Django 4.2.13 on 2024-05-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chief_options_alter_person_options_cake_chief')
    ]

    operations = [
    ]
