# Generated by Django 4.2.13 on 2024-05-25 18:01

from django.db import migrations


def create_default_chief(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Chief = apps.get_model('main', 'Chief')
    if not User.objects.filter(username='default_chief').exists():
        temp_user = Chief.objects.create_user(username='default_chief', password='default_password')
        temp_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),  # Проверьте правильный номер миграции auth
    ]

    operations = [
        migrations.RunPython(create_default_chief),
    ]

