# Generated by Django 4.2.13 on 2024-05-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20240525_2300'),
        ('main', '0006_add_default_chief'),
    ]

    operations = [
    ]
