# Generated by Django 4.2.13 on 2024-05-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_0005_merge_20240525_2300_0006_add_default_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='chief',
            field=models.ForeignKey(default=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='main.chief', verbose_name='Кондитер'),
        ),
    ]
